name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: npm update
          start: npx cypress run -e TAGS='@Regression or @Smoke' --browser chrome --spec $(node cypress-parallel.js ${{ matrix.containers }} 2)
          